# Generated by Django 3.1.4 on 2020-12-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='deals',
            field=models.CharField(choices=[('E', 'Exchange'), ('S', 'Sale'), ('D', 'Donate')], default='E', max_length=1),
        ),
    ]
