# Generated by Django 3.1.4 on 2020-12-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201212_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trading',
            old_name='deals',
            new_name='deal',
        ),
    ]
