# Generated by Django 3.1.4 on 2020-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201212_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='date',
            field=models.DateField(verbose_name='Trading Date'),
        ),
    ]
