# Generated by Django 3.1.4 on 2020-12-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201213_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('century', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trading',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='coin',
            name='bills',
            field=models.ManyToManyField(to='main_app.Bill'),
        ),
    ]
